import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type AuditResult = {
  overallScore: number;
  wasteScore: number;
  maturityLevel: string;
  monthlySpend: number;
  yearlySpend: number;
  estimatedMonthlySavings: number;
  estimatedYearlySavings: number;
  spendPerEmployee: number;
  benchmarkLabel: string;
  duplicateToolRisk: string;
  seatWasteRisk: string;
  apiVolatilityRisk: string;
  credexFit: boolean;
  findings: {
    title: string;
    description: string;
    severity: string;
    category: string;
  }[];
  recommendations: {
    title: string;
    description: string;
    action: string;
    estimatedMonthlySavings: number;
    priority: string;
  }[];
};

type AIReport = {
  executiveSummary: string;
  scoreExplanation: string;
  keyRisks: {
    title: string;
    description: string;
    severity: string;
  }[];
  recommendedActions: {
    title: string;
    description: string;
    impact: string;
  }[];
  finalVerdict: string;
};

type AuditInput = {
  teamName?: string;
  teamSize?: number;
  workflow?: string;
  tools?: {
    name: string;
    plan: string;
    monthlySpend: number;
    seats: number;
    frequency: string;
    ownerTeam: string;
    importance: string;
  }[];
};

type GenerateAuditPdfArgs = {
  result: AuditResult;
  aiReport: AIReport | null;
  auditInput: AuditInput | null;
};

const COLORS = {
  black: "#0f172a",
  slate: "#475569",
  lightSlate: "#f8fafc",
  border: "#e2e8f0",
  magenta: "#d946ef",
  magentaLight: "#fdf4ff",
  green: "#10b981",
  orange: "#f97316",
  red: "#ef4444",
};

function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  doc.setFillColor(COLORS.black);
  doc.rect(0, 0, 210, 34, "F");

  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(title, 14, 17);

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor("#cbd5e1");
    doc.text(subtitle, 14, 25);
  }

  doc.setFillColor(COLORS.magenta);
  doc.roundedRect(174, 10, 22, 10, 3, 3, "F");
  doc.setTextColor("#ffffff");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("CREDEX", 179, 16.5);
}

function addFooter(doc: jsPDF, pageNumber: number) {
  doc.setDrawColor(COLORS.border);
  doc.line(14, 285, 196, 285);

  doc.setTextColor("#94a3b8");
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by Credex AI Spend Audit", 14, 291);
  doc.text(`Page ${pageNumber}`, 184, 291);
}

function addSectionTitle(doc: jsPDF, title: string, y: number) {
  doc.setTextColor(COLORS.black);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(title, 14, y);

  doc.setDrawColor(COLORS.magenta);
  doc.setLineWidth(1.2);
  doc.line(14, y + 3, 48, y + 3);
}

function addMetricCard(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  label: string,
  value: string,
  color = COLORS.black,
) {
  doc.setFillColor("#ffffff");
  doc.setDrawColor(COLORS.border);
  doc.roundedRect(x, y, w, 28, 4, 4, "FD");

  doc.setTextColor("#64748b");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.text(label.toUpperCase(), x + 5, y + 8);

  doc.setTextColor(color);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text(value, x + 5, y + 21);
}

function addWrappedText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight = 5,
) {
  const lines = doc.splitTextToSize(text || "-", maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

function getRiskColor(risk: string) {
  if (risk === "HIGH") return COLORS.red;
  if (risk === "MEDIUM") return COLORS.orange;
  return COLORS.green;
}

function addRiskPill(doc: jsPDF, risk: string, x: number, y: number) {
  doc.setFillColor(getRiskColor(risk));
  doc.roundedRect(x, y - 5, 24, 8, 3, 3, "F");

  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.text(risk, x + 3, y);
}

function addProgressBar(
  doc: jsPDF,
  x: number,
  y: number,
  label: string,
  value: number,
  color: string,
) {
  doc.setTextColor(COLORS.black);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(label, x, y);

  doc.setTextColor(COLORS.slate);
  doc.text(`${value}/100`, x + 155, y);

  doc.setFillColor("#e2e8f0");
  doc.roundedRect(x, y + 4, 170, 6, 3, 3, "F");

  doc.setFillColor(color);
  doc.roundedRect(x, y + 4, Math.min(value, 100) * 1.7, 6, 3, 3, "F");
}

function addSavingsBars(doc: jsPDF, result: AuditResult, y: number) {
  const current = result.monthlySpend;
  const optimized = Math.max(result.monthlySpend - result.estimatedMonthlySavings, 0);
  const max = Math.max(current, optimized, 1);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(COLORS.black);
  doc.text("Spend comparison", 14, y);

  const bars = [
    { label: "Current", value: current, color: COLORS.black },
    { label: "Optimized", value: optimized, color: COLORS.magenta },
  ];

  bars.forEach((bar, index) => {
    const rowY = y + 10 + index * 15;
    const width = (bar.value / max) * 130;

    doc.setTextColor(COLORS.slate);
    doc.setFontSize(8);
    doc.text(bar.label, 14, rowY);

    doc.setFillColor("#e2e8f0");
    doc.roundedRect(44, rowY - 5, 130, 7, 3, 3, "F");

    doc.setFillColor(bar.color);
    doc.roundedRect(44, rowY - 5, width, 7, 3, 3, "F");

    doc.setTextColor(COLORS.black);
    doc.setFont("helvetica", "bold");
    doc.text(`$${bar.value}`, 178, rowY);
  });
}

export function generateAuditPdf({
  result,
  aiReport,
  auditInput,
}: GenerateAuditPdfArgs) {
  const doc = new jsPDF("p", "mm", "a4");

  // PAGE 1
  addHeader(
    doc,
    "AI Spend Audit Report",
    auditInput?.teamName
      ? `${auditInput.teamName} - ${auditInput.workflow || "AI stack"}`
      : "Generated audit summary",
  );

  doc.setFillColor(COLORS.magentaLight);
  doc.roundedRect(14, 46, 182, 34, 6, 6, "F");

  doc.setTextColor(COLORS.black);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Executive savings snapshot", 22, 59);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(COLORS.slate);
  doc.text(
    "A finance-friendly summary of AI spend waste, risk, and optimization opportunities.",
    22,
    68,
  );

  addMetricCard(doc, 14, 92, 42, "Efficiency", `${result.overallScore}/100`);
  addMetricCard(doc, 61, 92, 42, "Waste Index", `${result.wasteScore}/100`, COLORS.magenta);
  addMetricCard(doc, 108, 92, 42, "Monthly Save", `$${result.estimatedMonthlySavings}`, COLORS.green);
  addMetricCard(doc, 155, 92, 41, "Annual Save", `$${result.estimatedYearlySavings}`, COLORS.magenta);

  addSectionTitle(doc, "Score interpretation", 138);

  addProgressBar(doc, 14, 152, "AI Efficiency Score", result.overallScore, COLORS.green);
  addProgressBar(doc, 14, 173, "Spend Waste Index", result.wasteScore, COLORS.magenta);

  addSavingsBars(doc, result, 202);

  addSectionTitle(doc, "AI-generated executive summary", 244);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(COLORS.slate);
  addWrappedText(
    doc,
    aiReport?.executiveSummary ||
      "This audit identifies AI spend optimization opportunities based on tool usage, seat counts, plan fit, API volatility, and billing structure.",
    14,
    257,
    182,
    5,
  );

  addFooter(doc, 1);

  // PAGE 2
  doc.addPage();
  addHeader(doc, "Risk & Findings", "Key audit signals generated by the rules engine");

  addSectionTitle(doc, "Risk levels", 48);

  const risks = [
    ["Duplicate Tool Risk", result.duplicateToolRisk],
    ["Seat Waste Risk", result.seatWasteRisk],
    ["API Volatility Risk", result.apiVolatilityRisk],
  ];

  risks.forEach(([label, risk], index) => {
    const y = 64 + index * 19;

    doc.setFillColor("#ffffff");
    doc.setDrawColor(COLORS.border);
    doc.roundedRect(14, y - 9, 182, 14, 4, 4, "FD");

    doc.setTextColor(COLORS.black);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(label, 20, y);

    addRiskPill(doc, risk, 164, y);
  });

  addSectionTitle(doc, "Audit findings", 134);

  let y = 150;

  result.findings.slice(0, 6).forEach((finding, index) => {
    if (y > 255) {
      doc.addPage();
      addHeader(doc, "Risk & Findings", "Continued");
      y = 50;
    }

    doc.setFillColor(index % 2 === 0 ? COLORS.lightSlate : "#ffffff");
    doc.setDrawColor(COLORS.border);
    doc.roundedRect(14, y - 7, 182, 30, 4, 4, "FD");

    doc.setTextColor(COLORS.black);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(finding.title, 20, y);

    addRiskPill(doc, finding.severity, 164, y);

    doc.setTextColor(COLORS.slate);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    addWrappedText(doc, finding.description, 20, y + 8, 138, 4);

    doc.setTextColor(COLORS.magenta);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.text(finding.category.replaceAll("_", " "), 20, y + 22);

    y += 38;
  });

  addFooter(doc, 2);

  // PAGE 3
  doc.addPage();
  addHeader(doc, "Recommendation Roadmap", "Prioritized actions and savings");

  addSectionTitle(doc, "Top recommendations", 48);

  autoTable(doc, {
    startY: 58,
    head: [["Priority", "Recommendation", "Action", "Monthly savings"]],
    body: result.recommendations.map((rec) => [
      rec.priority,
      rec.title,
      rec.action,
      `$${rec.estimatedMonthlySavings}`,
    ]),
    styles: {
      font: "helvetica",
      fontSize: 8,
      cellPadding: 3,
      valign: "middle",
    },
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 24 },
      1: { cellWidth: 54 },
      2: { cellWidth: 72 },
      3: { cellWidth: 30, halign: "right" },
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 14;

  addSectionTitle(doc, "Final verdict", finalY);

  doc.setFillColor(COLORS.black);
  doc.roundedRect(14, finalY + 10, 182, 44, 6, 6, "F");

  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Recommended next step", 22, finalY + 23);

  doc.setTextColor("#cbd5e1");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  addWrappedText(
    doc,
    aiReport?.finalVerdict ||
      `This stack has an estimated annual optimization opportunity of $${result.estimatedYearlySavings}. Prioritize the highest-savings actions first, then review governance and billing structure.`,
    22,
    finalY + 33,
    160,
    4.5,
  );

  addFooter(doc, 3);

  // PAGE 4 - PER TOOL
  if (auditInput?.tools?.length) {
    doc.addPage();
    addHeader(doc, "Per-Tool Breakdown", "Current spend, usage fit, and action");

    autoTable(doc, {
      startY: 48,
      head: [["Tool", "Plan", "Spend", "Seats", "Usage", "Owner"]],
      body: auditInput.tools.map((tool) => [
        tool.name,
        tool.plan,
        `$${tool.monthlySpend}`,
        tool.seats,
        tool.frequency,
        tool.ownerTeam,
      ]),
      styles: {
        font: "helvetica",
        fontSize: 8,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: [217, 70, 239],
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
    });

    addFooter(doc, 4);
  }

  doc.save("credex-ai-spend-audit-report.pdf");
}